[package]
name = "rassfi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
rand = { version = "0.8.5" ,   features = ["getrandom"] }
rsa = "0.8.2"
srsa = "0.1.6"
zeroize = "1.6.0"
